### ISSUE TITLE
The sound is not playing

### ISSUE THREAD

**Issue by theFlyingcdd** [canaconZion/videoPlayer#11]
The sound is not playing. The project runs successfully, but there is no sound, only the video is playing. Can you help me?

**Comment by canaconZion** [comment]
Hello,
Thank you for your attention to my project. I'm sorry, but I've been quite busy with work recently, so the audio decoding thread for this player hasn't been completed yet. I expect to fix this bug later this week. Please stay tuned for my commits.

**Comment by canaconZion** [comment]
> The sound is not playing. The project runs successfully, but there is no sound, only the video is playing. Can you help me?

Hello,
Thank you for your attention to my project. I'm sorry, but I've been quite busy with work recently, so the audio decoding thread for this player hasn't been completed yet. I expect to fix this bug later this week. Please stay tuned for my commits.

**Comment by canaconZion** [comment]
> The sound is not playing. The project runs successfully, but there is no sound, only the video is playing. Can you help me?

Or you can refer to this example and try to add the audio decoding thread yourself.
https://github.com/canaconZion/streaming-practice/blob/main/ffmpeg/src/audio_player.cpp

**Comment by theFlyingcdd** [comment]
> > The sound is not playing. The project runs successfully, but there is no sound, only the video is playing. Can you help me?
> 
> Hello, Thank you for your attention to my project. I'm sorry, but I've been quite busy with work recently, so the audio decoding thread for this player hasn't been completed yet. I expect to fix this bug later this week. Please stay tuned for my commits.
Thank you for getting back to me. I will stay tuned for this project.

**Comment by theFlyingcdd** [comment]
Hello, I have reconfigured your latest uploaded project files, but I found that opening the video failed. Has the project not been completed yet?
![image](https://github.com/canaconZion/videoPlayer/assets/103501630/c090c37b-5e4e-48e2-a700-2a86689d5b90)
我用的Qt是5.13MinGw64，ffmpeg配的lib是4.4，SDL是2.28.2，不知道为啥出错了，如果方便的话，能邮箱交流一下吗1031001716@qq.com

**Comment by theFlyingcdd** [comment]
> 您好，我已经重新配置了您最新上传的项目文件，但我发现打开视频失败。项目尚未完成吗？ ![图像](https://user-images.githubusercontent.com/103501630/267262547-c090c37b-5e4e-48e2-a700-2a86689d5b90.png) 我用的Qt是5.13MinGw64，ffmpeg配的lib是4.4，SDL是2.28.2，不知道为啥出错了，如果方便的话，能邮箱交流一下吗 [1031001716@qq.com](mailto:1031001716@qq.com)


现在我发现在decode_video_thread.cpp的第373行注释掉”av_packet_unref(packet);“可成功运行，但还是没有声音

**Comment by canaconZion** [comment]
> > 您好，我已经重新配置了您最新上传的项目文件，但我发现打开视频失败。项目尚未完成吗？ ![图像](https://user-images.githubusercontent.com/103501630/267262547-c090c37b-5e4e-48e2-a700-2a86689d5b90.png) 我用的Qt是5.13MinGw64，ffmpeg配的lib是4.4，SDL是2.28.2，不知道为啥出错了，如果方便的话，能邮箱交流一下吗 [1031001716@qq.com](mailto:1031001716@qq.com)
> 
> 现在我发现在decode_video_thread.cpp的第373行注释掉”av_packet_unref(packet);“可成功运行，但还是没有声音
声音解码的线程已经完成了，可以pull最新的main试一下

**Comment by canaconZion** [comment]
> > 您好，我已经重新配置了您最新上传的项目文件，但我发现打开视频失败。项目尚未完成吗？ ![图像](https://user-images.githubusercontent.com/103501630/267262547-c090c37b-5e4e-48e2-a700-2a86689d5b90.png) 我用的Qt是5.13MinGw64，ffmpeg配的lib是4.4，SDL是2.28.2，不知道为啥出错了，如果方便的话，能邮箱交流一下吗 [1031001716@qq.com](mailto:1031001716@qq.com)
> 
> 现在我发现在decode_video_thread.cpp的第373行注释掉”av_packet_unref(packet);“可成功运行，但还是没有声音

audio的解码线程已经完成了，可以pull最新的代码试一下
